export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_QUERY = 'SET_QUERY'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_DISCS = 'SET_DISCS'

export const SET_F_DISCS = 'SET_F_DISCS'

export const SET_DISCARD_DISCS = 'SET_DISCARD_DISCS'

export const SET_ALBUMS = 'SET_ALBUMS'

export const SET_FAVORITE_SINGERS = 'SET_FAVORITE_SINGERS'

export const SET_FM_SWITCH = 'SET_FM_SWITCH'

export const SET_HOMEPAGE = 'SET_HOMEPAGE'

export const SET_LOGIN_USER = 'SET_LOGIN_USER'

